About Us Page
Pamanaa/pamana-website pull request #11
Opened 2024-07-30 06:28 UTC by jejeromemngls15

# [Title of PR]

## Details
- Created the draft for all the sections of About Us page.

## Juxtaposition

## Additional Notes

- Page is not yet responsive 
- Map is not yet integrated
- No Footer

2024-08-11 10:08 UTC, carlmitzchel requested changes

2024-08-11 10:08 UTC, carlmitzchel commented on src/app/about-us/page.tsx
Might consider using `wave component` separately to enhance quality.

![image](https://github.com/user-attachments/assets/fdbfdba9-a55e-48c1-9d34-4265817e704a)

2024-08-11 10:08 UTC, carlmitzchel commented on src/app/about-us/page.tsx
Experiment with tailwind's `leading-` to minimize vertical spaces in sentences. 
![image](https://github.com/user-attachments/assets/5c367913-2e5c-4520-97ab-154171731a25)

2024-08-11 10:08 UTC, carlmitzchel commented on src/app/about-us/page.tsx
Use the `barrel` method for importing and exporting components. You can check `/components` folder in the main branch.

2024-08-11 10:30 UTC, JoshuaEntrata reviewed
create index file for components. refer to the components used in Amenities and Offers pages

2024-08-12 08:00 UTC, jejeromemngls15 commented on src/app/about-us/page.tsx
okay na yung barrel and tailwind leading. not sure with the wave component if okay yung approach ko, pacheck nalng

2024-08-15 13:22 UTC, carlmitzchel approved these changes

2024-08-16 04:52 UTC, merged