Home Page
Pamanaa/pamana-website pull request #12
Opened 2024-08-07 08:39 UTC by saralimeta

# Home Page

## Details

- created the home page

## Juxtaposition

![image](https://github.com/user-attachments/assets/ef554435-0ab7-4775-82bf-47647c694ac2)
![image](https://github.com/user-attachments/assets/55de7e04-a390-447f-aab8-f35c6dffa82c)
![image](https://github.com/user-attachments/assets/1e119175-d870-4509-a6eb-c2fb33d776a0)
![image](https://github.com/user-attachments/assets/b8605300-a5c5-4c28-9c10-f8b41447c592)
![image](https://github.com/user-attachments/assets/556bce1b-a4bf-4741-ac5f-e8f7c5273d00)
![image](https://github.com/user-attachments/assets/3ab3915f-15ee-4620-a0c3-39357754fd65)
![image](https://github.com/user-attachments/assets/33d101ce-dbf7-4597-b5f7-d43c4d7f1c7f)
![image](https://github.com/user-attachments/assets/bbbdb04b-fd47-4b6b-9166-0217d7078823)
![image](https://github.com/user-attachments/assets/a04543af-95ba-4b71-b050-3b26e2ac7f55)
![image](https://github.com/user-attachments/assets/7b64b058-7ff4-446e-866d-4c0f6515a435)

## Additional Notes

- No footer yet
- Not responsive
- Video still missing (replaced with a temporary image)
- Carousel component is not yet working
- temporarily changed images (not yet finalized)
- star ratings not yet working and still different from the figma design

2024-08-11 10:02 UTC, carlmitzchel requested changes

2024-08-11 10:02 UTC, carlmitzchel commented on src/app/features/auth/components/Card/card.tsx
Move images to `src/public/images/` folder, then fix corresponding import errors

2024-08-11 10:02 UTC, carlmitzchel commented on src/app/page.tsx
"Savor Culinary Delights" and the elements underneath it aren't centered
![image](https://github.com/user-attachments/assets/8d1183c3-02ae-49f3-85f9-a1bceb66a0e9)

2024-08-11 10:02 UTC, carlmitzchel commented on src/app/page.tsx
As well as "Celebrate your Special Occasion"
![image](https://github.com/user-attachments/assets/8fe71ede-203e-4a67-9358-45b30dc21e80)

2024-08-11 10:02 UTC, carlmitzchel commented on src/app/page.tsx
"Add a review" button is not centered
![image](https://github.com/user-attachments/assets/522f6837-b70c-44fe-a3a8-200c60fb2969)

2024-08-11 10:02 UTC, carlmitzchel commented on src/app/page.tsx
Follow the "barrel" method in importing and exporting components. See `components` folder in main branch

2024-08-11 10:33 UTC, JoshuaEntrata commented on src/app/features/auth/components/Card/card.tsx
> +      <div className="-mt-14 mb-6 ml-[380px] mr-[50px] flex">
Use `react-icons` instead of images for the icons

2024-08-11 10:34 UTC, JoshuaEntrata commented on src/app/features/auth/components/Card/card.tsx
> +    <div className="}] mr-10 h-[570px] w-[550px] rounded-2xl bg-[rgb(254,255,243)] shadow-xl">
try using `flexbox` when styling this component para di hard coded yung margins at maging easier satin pag nagapply ng responsiveness sa pages at components

2024-08-11 10:37 UTC, JoshuaEntrata commented on src/app/features/auth/components/reviews.tsx
> +        <i className="h-12 w-12">&#9733;</i>
use stars from `react-icons`

2024-08-19 12:01 UTC, carlmitzchel approved these changes

2024-08-19 12:01 UTC, merged