Amenities Pages
Pamanaa/pamana-website pull request #8
Opened 2024-07-18 08:53 UTC by JoshuaEntrata

# Amenities Pages

## Details

- Created initial pages for Amenities and Offers - Amenities.
- Created the Footer component.
- Added two new font styles in `tailwind.config.ts`.
- Installed `react-icons` .

## Juxtaposition

- Amenities Home Page 
![image](https://github.com/user-attachments/assets/dfb5fa1d-96fc-424e-b566-5a7f912333c2)
- Function Hall Page 
![image](https://github.com/user-attachments/assets/6e3dfa2f-9e0c-4d37-9957-c0c24af2f745)
- Swimming Pool Page 
![image](https://github.com/user-attachments/assets/9bfe2035-57a6-42f4-add5-850575298ecd)
- Souvenir Shop Page 
![image](https://github.com/user-attachments/assets/1c67df17-d180-42df-b65a-138f325b4812)

## Additional Notes

- `npm install`
- Follow the format of `index.tsx` files in the component directory for future PRs.
- All pages and components are not yet responsive and are currently catered for the default computer dimensions.
- The Carousel component does not yet match the one in the Figma. Will reconstruct this in the next PR.
- Need to replace the font style of body and link texts in `AmenitiesCard.tsx` with `lao-muang-dong`
- Images used are temporary.
- Used a sample video for the Amenities home page, which needs updating
- The `NewsletterInput.tsx` component is still static.

2024-07-28 15:06 UTC, carlmitzchel requested changes

2024-07-28 15:06 UTC, carlmitzchel commented on src/components/Carousel/Carousel.tsx
Implement movement indicators (Left & Right arrows) for better accessibility

2024-07-28 15:08 UTC, carlmitzchel commented
Lao Muang Don is integrated in PR #9 
<img width="408" alt="image" src="https://github.com/user-attachments/assets/b10f9800-258e-4618-9e35-62d1f22ece8c">

2024-07-28 15:21 UTC, JoshuaEntrata commented on src/components/Carousel/Carousel.tsx
next PR pa yung para sa carousel

2024-07-29 09:21 UTC, JoshuaEntrata commented
### What did I do?
- Applied the updates for `lao-muang` font style in PR#9

2024-08-05 05:47 UTC, carlmitzchel approved these changes

2024-08-05 06:02 UTC, merged